name: nix-macos-pytorch

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build
      run: |
        mkdir -p ~/.config/nixpkgs
        echo  '{ allowUnfree = true; }' >  ~/.config/nixpkgs/config.nix
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix use pytorch-world
        nix-build ./release.nix -A pytorch -A pytorch-mkl
